# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qpicasa/ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(798, 626)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_7 = QtWidgets.QFrame(self.centralwidget)
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 51))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(338, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.frame_7)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.gridLayout.addWidget(self.frame_7, 0, 0, 1, 2)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.treeView_scandirs = QtWidgets.QTreeView(self.frame_2)
        self.treeView_scandirs.setIndentation(10)
        self.treeView_scandirs.setObjectName("treeView_scandirs")
        self.treeView_scandirs.header().setVisible(False)
        self.verticalLayout.addWidget(self.treeView_scandirs)
        self.gridLayout.addWidget(self.frame_2, 1, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 71))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setMaximumSize(QtCore.QSize(51, 55))
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_5)
        self.label.setMaximumSize(QtCore.QSize(45, 39))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/icon_folder"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.horizontalLayout_3.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_dir_name = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        self.lbl_dir_name.setFont(font)
        self.lbl_dir_name.setStyleSheet("color: rgb(170, 170, 127)")
        self.lbl_dir_name.setText("")
        self.lbl_dir_name.setObjectName("lbl_dir_name")
        self.verticalLayout_2.addWidget(self.lbl_dir_name)
        self.lbl_cdate = QtWidgets.QLabel(self.frame_6)
        self.lbl_cdate.setText("")
        self.lbl_cdate.setObjectName("lbl_cdate")
        self.verticalLayout_2.addWidget(self.lbl_cdate)
        self.horizontalLayout_3.addWidget(self.frame_6)
        self.verticalLayout_4.addWidget(self.frame_4)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 46))
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_slidshow = QtWidgets.QPushButton(self.frame_3)
        self.btn_slidshow.setMaximumSize(QtCore.QSize(31, 34))
        self.btn_slidshow.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icon_slideshow"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_slidshow.setIcon(icon)
        self.btn_slidshow.setObjectName("btn_slidshow")
        self.verticalLayout_3.addWidget(self.btn_slidshow)
        self.verticalLayout_4.addWidget(self.frame_3)
        self.frame_thumbs_container = QtWidgets.QFrame(self.frame)
        self.frame_thumbs_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_thumbs_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_thumbs_container.setObjectName("frame_thumbs_container")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_thumbs_container)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.listView_thumbs = QtWidgets.QListView(self.frame_thumbs_container)
        self.listView_thumbs.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.listView_thumbs.setDragEnabled(True)
        self.listView_thumbs.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.listView_thumbs.setIconSize(QtCore.QSize(0, 0))
        self.listView_thumbs.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.listView_thumbs.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.listView_thumbs.setMovement(QtWidgets.QListView.Snap)
        self.listView_thumbs.setLayoutMode(QtWidgets.QListView.Batched)
        self.listView_thumbs.setViewMode(QtWidgets.QListView.IconMode)
        self.listView_thumbs.setUniformItemSizes(False)
        self.listView_thumbs.setObjectName("listView_thumbs")
        self.gridLayout_2.addWidget(self.listView_thumbs, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.frame_thumbs_container)
        self.gridLayout.addWidget(self.frame, 1, 1, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.centralwidget)
        self.frame_8.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setLineWidth(2)
        self.frame_8.setMidLineWidth(0)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_5.setContentsMargins(5, 1, 5, 1)
        self.verticalLayout_5.setSpacing(1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_9 = QtWidgets.QFrame(self.frame_8)
        self.frame_9.setAutoFillBackground(False)
        self.frame_9.setStyleSheet("color: white;\n"
"background-color: rgb(86, 144, 182);\n"
"font-weight: bold")
        self.frame_9.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(201, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.lbl_selection_summary = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setBold(True)
        font.setWeight(75)
        self.lbl_selection_summary.setFont(font)
        self.lbl_selection_summary.setObjectName("lbl_selection_summary")
        self.horizontalLayout_4.addWidget(self.lbl_selection_summary)
        spacerItem2 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_5.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(self.frame_8)
        self.frame_10.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_6.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_6.setSpacing(1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem3 = QtWidgets.QSpacerItem(518, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.hslider_thumb_size = QtWidgets.QSlider(self.frame_10)
        self.hslider_thumb_size.setMaximumSize(QtCore.QSize(140, 16777215))
        self.hslider_thumb_size.setMaximum(256)
        self.hslider_thumb_size.setSingleStep(20)
        self.hslider_thumb_size.setSliderPosition(64)
        self.hslider_thumb_size.setOrientation(QtCore.Qt.Horizontal)
        self.hslider_thumb_size.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.hslider_thumb_size.setObjectName("hslider_thumb_size")
        self.horizontalLayout_6.addWidget(self.hslider_thumb_size)
        self.frame_11 = QtWidgets.QFrame(self.frame_10)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_tags = QtWidgets.QPushButton(self.frame_11)
        self.btn_tags.setObjectName("btn_tags")
        self.horizontalLayout_5.addWidget(self.btn_tags)
        self.horizontalLayout_6.addWidget(self.frame_11)
        self.verticalLayout_5.addWidget(self.frame_10)
        self.gridLayout.addWidget(self.frame_8, 2, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 798, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuThumbnail_Captions = QtWidgets.QMenu(self.menuView)
        self.menuThumbnail_Captions.setObjectName("menuThumbnail_Captions")
        self.menuFolder_View = QtWidgets.QMenu(self.menuView)
        self.menuFolder_View.setObjectName("menuFolder_View")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_FolderManager = QtWidgets.QAction(MainWindow)
        self.action_FolderManager.setObjectName("action_FolderManager")
        self.actionSmall_Thumbnails = QtWidgets.QAction(MainWindow)
        self.actionSmall_Thumbnails.setCheckable(True)
        self.actionSmall_Thumbnails.setObjectName("actionSmall_Thumbnails")
        self.actionNormal_Thumbnails = QtWidgets.QAction(MainWindow)
        self.actionNormal_Thumbnails.setCheckable(True)
        self.actionNormal_Thumbnails.setChecked(True)
        self.actionNormal_Thumbnails.setObjectName("actionNormal_Thumbnails")
        self.actionProperties = QtWidgets.QAction(MainWindow)
        self.actionProperties.setObjectName("actionProperties")
        self.actionTags = QtWidgets.QAction(MainWindow)
        self.actionTags.setObjectName("actionTags")
        self.actionSlideshow = QtWidgets.QAction(MainWindow)
        self.actionSlideshow.setObjectName("actionSlideshow")
        self.actionFilename = QtWidgets.QAction(MainWindow)
        self.actionFilename.setCheckable(True)
        self.actionFilename.setObjectName("actionFilename")
        self.actionFilename_2 = QtWidgets.QAction(MainWindow)
        self.actionFilename_2.setObjectName("actionFilename_2")
        self.actionFlat_View = QtWidgets.QAction(MainWindow)
        self.actionFlat_View.setCheckable(True)
        self.actionFlat_View.setObjectName("actionFlat_View")
        self.menuTools.addAction(self.action_FolderManager)
        self.menuThumbnail_Captions.addAction(self.actionFilename)
        self.menuThumbnail_Captions.addAction(self.actionFilename_2)
        self.menuFolder_View.addAction(self.actionFlat_View)
        self.menuView.addAction(self.actionSmall_Thumbnails)
        self.menuView.addAction(self.actionNormal_Thumbnails)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionProperties)
        self.menuView.addAction(self.actionTags)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionSlideshow)
        self.menuView.addSeparator()
        self.menuView.addAction(self.menuThumbnail_Captions.menuAction())
        self.menuView.addAction(self.menuFolder_View.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Search"))
        self.lbl_selection_summary.setText(_translate("MainWindow", "A long string of text description the curernt selection goes here"))
        self.btn_tags.setText(_translate("MainWindow", "Tags"))
        self.menuFile.setTitle(_translate("MainWindow", "Fi&le"))
        self.menuTools.setTitle(_translate("MainWindow", "&Tools"))
        self.menuAbout.setTitle(_translate("MainWindow", "Abo&ut"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuThumbnail_Captions.setTitle(_translate("MainWindow", "Thumbnail Captions"))
        self.menuFolder_View.setTitle(_translate("MainWindow", "Folder View"))
        self.action_FolderManager.setText(_translate("MainWindow", "&Folder Manager"))
        self.actionSmall_Thumbnails.setText(_translate("MainWindow", "Small Thumbnails"))
        self.actionNormal_Thumbnails.setText(_translate("MainWindow", "Normal Thumbnails"))
        self.actionProperties.setText(_translate("MainWindow", "Properties"))
        self.actionTags.setText(_translate("MainWindow", "Tags"))
        self.actionSlideshow.setText(_translate("MainWindow", "Slideshow"))
        self.actionFilename.setText(_translate("MainWindow", "None"))
        self.actionFilename_2.setText(_translate("MainWindow", "Filename"))
        self.actionFlat_View.setText(_translate("MainWindow", "Flat Folder View"))

import qpicasa_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

